- name: cart ansible
  hosts: cart 
  become: yes
  tasks:
  - name: download nodejs repo
    shell:  curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: install nodejs
    yum:
      name: nodejs
      state: installed
    

  
