
- name: check user exits
  hosts: localhost
  tasks: 
  - name: conditions check 
    ansible.builtin.command: id roboshop
    register: output1
    ignore_errors: true


  - name: check output 
    ansible.builtin.debug:
      msg: " print {{output1}}"
  - name: exist status 
    ansible.builtin.debug:
      msg: "exist status {{output1.rc}}"

  - name: create user 
    ansible.builtin.user:
      -name: roboshop 
    when: output1.rc!=0 