- name: local testing 
  hosts: localhost
  vars:
    directory: "/app"

  tasks:
  - name: check the directory in local 
    ansible.builtin.stat:
      path: "{{directory}}"
    register: app_path
  

  - name: exist status
    debug:
      msg: " exist status {{app_path.stat.exists}}"

  - name: create the directory 
    ansible.builtin.command: mkdir /app
    when: app_path.stat.exists == "false"
  
  

    