
- name: check variables
  hosts: localhost
  tasks:
  - name: loop variables
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: nginx, state: remove}
    - {name: mysql, state: remove}
    - {name: varnish, state: installed}

