- name: nginx_install and run it 
  hosts: nginx
  tasks:
  - name: installing_nginx
    ansible.builtin.yum:
      name: nginx
      state: installed 
  
- name: starting nginx
  hosts: nginx
  tasks:
    name: start nginx
    ansible.builtin.yum:
      name: nginx
      state: started
  

