- name: web application
  hosts: nginx
  become: yes
  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: installed
      

  - name:  start the service
    yum: 
      name: nginx
      state: present
      
  # - name:  nginx point 
  #   uri: 
  #     url: http://"{{nginx-public}}".com:80
    
    
  #   register: output
  
  # - name: nginx verification
  #   debug:
  #     mdg: " output is done"
  #   when: output.status.code == 200

  - name: list all files in nginx folder
    find:
      path: /usr/share/nginx/html
    register: list_folder


  - name: print files
    vars:
      list_files: {{list_folder.files | map (attribute='path')}}
    debug:
      msg: " print files {{list_files}}"
  


  - name: remove the files in nginx folder
    file:
      path: "{{items}}"
      state: absent
    with_items: "{{list_files}}"



    


  
    
  

      
      
  
  