- name: web application
  hosts: nginx
  become: yes
  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: installed
      

  - name:  start the service
    yum: 
      name: nginx
      state: present
      
  # - name:  nginx point 
  #   uri: 
  #     url: http://"{{nginx-public}}".com:80
    
    
  #   register: output
  
  # - name: nginx verification
  #   debug:
  #     mdg: " output is done"
  #   when: output.status.code == 200

  # - name: list all files in nginx folder
  #   find:
  #     path: /usr/share/nginx/html
  #   register: list_folder


  # - name: print files
    
  #   debug:
  #     "{{list_folder.files | map (attribute='path')}}"
  #   register: list_files
  


  # - name: remove the files in nginx folder
  #   file:
  #     path: "{{item}}"
  #     state: absent
  #   with_items: "{{list_files}}"



    
  - name: Recursively remove directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: download artificat 
    shell: curl -o /tmp/web.zip https://roboshop-builds.s3.amazonaws.com/web.zip
     
  - name: create html directory 
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory
    
  - name: unzip the archive
    ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html
      remote_src: yes

   
  - name: copy the roboshop conf
    copy: 
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf 

  - name: restart nginx
    service:
      name: nginx
      state: restarted

  
    
  

      
      
  
  